# #
# Import R packages needed for the UI
library(shiny)
library(shinycssloaders)
library(DT)

# Begin UI for the R + reticulate example app
ui <- fluidPage(
  
  titlePanel('Example app: Using R Shiny + reticulate'),
  
  sidebarLayout(
    
    # ---------------- Sidebar panel with changeable inputs ----------------- #
    sidebarPanel(
      
      h4('Inputs to pure R functions'),
      radioButtons('dist', 
                   'Distribution type:',
                   choices = c('Normal' = 'norm',
                               'Uniform' = 'unif', 
                               'Log-normal' = 'lnorm', 
                               'Exponential' = 'exp')),
      br(),
      sliderInput('n',
                  'Number of observations:',
                  value = 5000,
                  min = 100,
                  max = 10000),
      hr(),
      
      h4('Inputs to Python functions called by reticulate'),
      textInput('str',
                'Text to display',
                value = 'This text is being printed by a Python function!'),
      numericInput('x',
                   'x value',
                   value = 1),
      numericInput('y',
                   'y value',
                   value = 2)
    ),
    
    # ---------------- Sidebar panel with changeable inputs ----------------- #
    mainPanel(
      
      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = 'tabs',
                  tabPanel('Using R and Python functions', 
                           br(),
                           h3('Outputs generated with pure R'),
                           br(),
                           withSpinner(plotOutput('plot')),
                           br(),
                           h3('Outputs generated by Python functions via reticulate'),
                           verbatimTextOutput('message'),
                           br(),
                           'Use the numpy Python package to add two numbers',
                           verbatimTextOutput('xy')),
                  tabPanel('Architecture Info', 
                           h3('Current architecture info'),
                           '(These values will change when app is run locally vs on Shinyapps.io)',
                           hr(),
                           withSpinner(DT::dataTableOutput('sysinfo')),
                           br(),
                           verbatimTextOutput('which_python'),
                           verbatimTextOutput('python_version'),
                           verbatimTextOutput('ret_env_var'),
                           verbatimTextOutput('venv_root')
                  )
      )
    )
  )
)

############
# # This is the user-interface definition of a Shiny web application. You can
# # run the application by clicking 'Run App' above.
# #
# # Find out more about building applications with Shiny here:
# #
# #    http://shiny.rstudio.com/
# #
# 
# library(shiny)
# 
# # Define UI for application that draws a histogram
# fluidPage(
# 
#     # Application title
#     titlePanel("Old Faithful Geyser Data"),
# 
#     # Sidebar with a slider input for number of bins
#     sidebarLayout(
#         sidebarPanel(
#             sliderInput("bins",
#                         "Number of bins:",
#                         min = 1,
#                         max = 50,
#                         value = 30)
#         ),
# 
#         # Show a plot of the generated distribution
#         mainPanel(
#             plotOutput("distPlot")
#         )
#     )
# )





###############
# library(shiny)
# 
# # Define UI for application that draws a histogram
# fluidPage(
#   # Application title
#   titlePanel("Old Faithful Geyser Data"),
#   
#   # Sidebar with a slider input for number of bins
#   sidebarLayout(
#     sidebarPanel(
#       sliderInput("bins",
#                   "Number of bins:",
#                   min = 1,
#                   max = 50,
#                   value = 30)
#     ),
#     
#     # Show a plot of the generated distribution
#     mainPanel(
#       plotOutput("distPlot")
#     )
#   )
# )
# 
